---
version: "3"
services:
    reverse-proxy:
        image: nginxstuff
        container_name: reverse_proxy
        depends_on:
            - bookstack
            - bookstack_db
        ports:
            - 80:80
        volumes:
            - /root/dockerstuff/reverseproxy/nginx.conf:/etc/nginx/nginx.conf
            - /root/dockerstuff/reverseproxy/bookstack.conf:/etc/nginx/conf.d/bookstack.conf
    bookstack:
        image: lscr.io/linuxserver/bookstack
        container_name: bookstack
        environment:
            - PUID=1000
            - PGID=1000
            - APP_URL=
            - DB_HOST=bookstack_db
            - DB_USER=bookstack
            - DB_PASS=bookstack
            - DB_DATABASE=bookstackapp
        volumes:
            - /root/bookstack/config:/config
        ports:
            - 6875:80
        restart: unless-stopped
        depends_on:
            - bookstack_db
    bookstack_db:
        image: lscr.io/linuxserver/mariadb
        container_name: bookstack_db
        environment:
            - PUID=1000
            - PGID=1000
            - MYSQL_ROOT_PASSWORD=bookstack
            - TZ=Europe/London
            - MYSQL_DATABASE=bookstackapp
            - MYSQL_USER=bookstack
            - MYSQL_PASSWORD=bookstack
        volumes:
            - /root/bookstack/dbconfig:/config
        restart: unless-stopped